name: 'DK Git Salesforce CLI Setup'
description: 'Configuring Salesforce CLI with user details'

inputs:
  user_name:
    required: true
    type: string
  instance_url:
    type: string
    default: https://login.salesforce.com
  password:
    required: true
    description: combination of <password>:<security_token>
  sfdc_client_id:
    required: true
    description: Consumer Key of a connected App created within salesforce
  sfdc_client_secret:
    required: true
    description: Consumer Secret of a connected App created within salesforce
runs:
  using: "composite"
  steps:
    - id: sfdc_auth
      uses: karamchandanid/sfdc-credentials-auth@v2
      with:
        sfdc_client_id: ${{ inputs.sfdc_client_id }}
        sfdc_client_secret: ${{ inputs.sfdc_client_secret }}
        user_name: ${{ inputs.user_name }}
        password: ${{ inputs.password }}
        login_url: ${{ inputs.instance_url}}
    - id: sfdc_details
      shell: bash
      name: Display auth details
      run: |
        echo ${{ steps.sfdc_auth.outputs.instance_url }}
        echo ${{ steps.sfdc_auth.outputs.id }}
        echo ${{ steps.sfdc_auth.outputs.access_token }}